const ENG_MSG_DEFAULT_CHAR_LENGTH = 160;
const TH_MSG_DEFAULT_CHAR_LENGTH = 70;
const ENG_NEXT_CHAR_LENGTH = 153;
const TH_NEXT_CHAR_LENGTH = 67;
const DOUBLE_BYTES_CHAR = [12, 91, 92, 93, 94, 123, 124, 125, 126];
const MAX_CHAR_LENGTH_ASC = 70;
const MAX_CHAR_LENGTH_UNI = 160;
const NUMBER_REGEX = /[^0-9.]/g;
export default {
    ENG_MSG_DEFAULT_CHAR_LENGTH,
    TH_MSG_DEFAULT_CHAR_LENGTH,
    ENG_NEXT_CHAR_LENGTH,
    TH_NEXT_CHAR_LENGTH,
    DOUBLE_BYTES_CHAR,
    MAX_CHAR_LENGTH_ASC,
    MAX_CHAR_LENGTH_UNI,
    NUMBER_REGEX,
};
